### ISSUE TITLE
rumors: no new rumors since OTA

### ISSUE THREAD

**Issue by bonbud-macryg** [Fang-/suite#11]
I stopped seeing anything new in %rumors since a couple of days after the recent OTA, where before it was always very active. Might be worth mentioning my Groups subscriptions were all out of sync after the update.

I've tried suspending-reviving %rumors and %pals, re-installing %rumors and %pals, removing and re-adding pals, and dotposting to rumors. I've added my planet as a pal from a moon and the moon sees nothing in %pals either. Is there anything I can do on my end to diagnose what's going wrong?

**Comment by Fang-** [comment]
Hmm, needing to `|revive %rumors` post-ota is the first thing that came to mind.

You can run `:rumors +dbug [%outgoing ~]` and `:rumors +dbug [%incoming ~]` to see if there's any subscriptions there at all, and whether they've gotten acked yet.

Could also be the infamous subscription desync bug, for which a patch will release soon.

**Comment by bonbud-macryg** [comment]
`outgoing` gets me `ackd=%.y` for most of my mutual pals. One `acked=%.n` is for a ship with a bad connection and another is from someone I know is active. `path=/targets ackd=%.y` on both counts for the %pals subscriptions.

I see three subscriptions from `incoming` out of ten contacts in my %pals. Two are from leeches, one from a pal. One of those is from a leeche who just added me right now... and seems to have kicked rumors back into life?

I'll run those commands later and see what happens, maybe more rumors will come in. But if there's a patch coming soon that should fix this then it's not a big issue :)
