### ISSUE TITLE
rumors: max length

### ISSUE THREAD

**Issue by tomholford** [Fang-/suite#15]
Sadly longpost spam is becoming a thing. What would a sensible default limit look like? Or could some kind of rolling window work? ie, *n* chars allowed over *n* posts. of course that's way more work, so a simple cap is probably sufficient

![image](https://user-images.githubusercontent.com/16504501/228024892-74803f96-330e-4ea9-97d6-74982ebeeacf.png)

**Comment by Fang-** [comment]
One step ahead of you. Upcoming release (w/ b014489) will fix this. Thanks for taking notice!

**Comment by tomholford** [comment]
closed by https://github.com/Fang-/suite/commit/b01448946f5aeb091a17e7d8cca41d8e44a5c6ef
