### ISSUE TITLE
urb.pal.dev is down

### ISSUE THREAD

**Issue by narskidan** [Fang-/suite#16]
I noticed in Landscape that the icon for Million Dollar Urbit app is broken:

<img width="296" alt="Screenshot 2023-12-14 at 22 03 53" src="https://github.com/Fang-/suite/assets/104947308/0f94fa50-cad6-4204-b638-4a55e1a054c4">

Upon investigation, it turns out this icon is served from https://urb.pal.dev/million/image.svg

When I try connecting to this, I get connection refused. I also tried connecting to urb.pal.dev via Tor (in case it was something particular to my local network) and no dice.

Seems urb.pal.dev is down?

**Comment by Fang-** [comment]
No longer down (for now). We try to baby-sit paldev but it falls over out of sight occasionally. Thanks for the report!
