### ISSUE TITLE
duiker: ;delete n doesn't take into account the current page

### ISSUE THREAD

**Issue by ryjm** [Fang-/suite#2]
I tried to delete a torrent that was on the second page (sequence was `>` and `;delete 4`), but it deleted the torrent on the first page instead.

![image](https://user-images.githubusercontent.com/2065299/99921797-da3fea00-2cfa-11eb-9218-59caf736cdaf.png)

**Comment by Fang-** [comment]
Oof. A friend had pointed out that selection doesn't respect page state, but I guess that naturally applies to other commands too. Sorry about the trouble, I'll get a fix for this in Soon™.

**Comment by ryjm** [comment]
damn that was fast, thanks!!
