### ISSUE TITLE
pals: adding yourself as a pal reports success but doesn't add the entry

### ISSUE THREAD

**Issue by lycurgus** [Fang-/suite#7]
If I add `~monted-tallex` (me) as a pal, the interface says it was processed successfully, but nothing actually changes (including after a reload). I feel like it should either show an error, or succeed - but should not report success without succeeding.

I can't predict what use other apps might have for a ship's list of pals but I feel like having yourself as a pal is probably not a very sensible thing to do? But then maybe there is some case for it and it's better to support the weird thing in case someone needs it...

From my reading of the code this is intentional (line 113) so it probably just needs some error reporting there :) I'd raise a PR for it but my hoon is not quite good enough to figure out what needs to be added.

**Comment by Fang-** [comment]
It indeed just silently no-ops. I believe the first draft had it as a crash, but then I thought "no-op is better". I'm... still somewhat on the fence about it. But regardless of the `on-poke` behavior, the ui implementation can definitely catch this and give an appropriate warning.
